apiVersion: v1
name: external-secrets
version: 0.0.0
dependencies: # A list of the chart requirements (optional)
  - name: external-secrets
    version: 1.2.1
    repository: https://charts.external-secrets.io/