# You can customize your values from this link https://artifacthub.io/packages/helm/hashicorp/vault and click on "DEFAULT VALUES"
# NOTE all values in above reference it must my chiled of name of Application in Chart.yaml (for e.g in below)

# vault:
#   global:
#     enabled: true