global:
  clusterDomain: zahra.local
  dnsService: kube-dns
  dnsNamespace: kube-system
chunksCache:
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 2Gi
monitoring:
  # Dashboards for monitoring Loki
  dashboards:
    # -- If enabled, create configmap with dashboards for monitoring Loki
    enabled: true
  serviceMonitor:
  # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
    enabled: true

loki:
  deploymentMode: SimpleScalable

  # —————————————————————
  # |   RUNTIME CONFIG   |
  # —————————————————————
  # (these fields become /etc/loki/config.yaml for every pod)
  structuredConfig:
    common:
      storage:
        s3:
          s3forcepathstyle: true
    ruler:
      storage:
        s3:
          s3forcepathstyle: true

  analytics:
    reporting_enabled: false
  auth_enabled: false
  commonConfig:
    replication_factor: 1

  limits_config:
    retention_period: 14d

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: minio.minio.svc.zahra.local:9000
      accessKeyId: loki
      secretAccessKey: admin1234567
      insecure: true
      s3forcepathstyle: true

  tracing:
    enabled: true

  # —————————————————————
  # | DEPLOYMENT SETTINGS |
  # —————————————————————
  # In SimpleScalable mode, you only control:
  #   write.replicas, read.replicas, backend.replicas
  # Anything else (distributor, ingester, querier, compactor, indexGateway)
  # is wired up internally by the chart.

  # 1) WRITE PATH (Distributor + Ingester under the hood)
  write:
    replicas: 3
    affinity: ""
    extraArgs:
      - "-config.expand-env=true"
    extraEnv:
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: loki-secret
            key: AWS_SECRET_ACCESS_KEY

  # 2) READ PATH (Querier under the hood)
  read:
    replicas: 3
    affinity: ""
    extraArgs:
      - "-config.expand-env=true"
    extraEnv:
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: loki-secret
            key: AWS_SECRET_ACCESS_KEY

  # 3) BACKEND (Compactor + IndexGateway under the hood)
  backend:
    replicas: 1
    affinity: ""
    extraArgs:
      - "-config.expand-env=true"
    extraEnv:
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: loki-secret
            key: AWS_SECRET_ACCESS_KEY
