apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  replicas: 30
  selector:
    matchLabels:
      app: busybox1
  template:
    metadata:
      labels:
        app: busybox1
    spec:
      schedulerName: cpu-scheduler
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          resources:
            requests:
              cpu: "1"

  # imagePullSecrets:
  #   - name: dockerhub-secret

