apiVersion: v1
name: postgres
version: 0.0.0
dependencies: # A list of the chart requirements (optional)
  - name: postgres
    version: 17.6
    repository: https://groundhog2k.github.io/helm-charts/