postgres:
  settings:
    superuser:
      secretKey: user
      value: postgres_admin
    superuserPassword:
      secretKey: password
      value: admin@123
      
  userDatabase:
    user:
      secretKey: user
      value: postgres_user
    password:
      secretKey: password
      value: admin@123