postgres:
  settings:
    superuser:
      # secretKey: user
      value: postgres
    superuserPassword:
      # secretKey: password
      value: admin@123
      
  userDatabase:
    name:
      # secretKey: postgres
      value: graviteeapim
    user:
      # secretKey: user
      value: postgres
    password:
      # secretKey: password
      value: admin@123