users:
 - accessKey: loki
   existingSecret: loki
   existingSecretKey: secret-key
   policy: readwrite
existingSecret: minio-access-key
# mode: distributed
# storageClass: ""
# volumeName: ""
# accessMode: ReadWriteOnce
# size: 1Gi
resources:
  requests:
    memory: 4Gi

persistence:
  size: 1G 

oidc:
  enabled: true
  configUrl: "http://keycloak.keycloak.svc/realms/master/.well-known/openid-configuration"
  clientId: "minio"
  clientSecret: ""
  # Provide existing client secret from the Kubernetes Secret resource, existing secret will have priority over `clientId` and/or `clientSecret``

  # claimName: "minio"
  # scopes: "openid,profile,email"
  # redirectUri: "http://localhost:9001/oauth_callback"
  # # Can leave empty
  # claimPrefix: ""
  # comment: ""
  # displayName: "SSO"


# image:
#   repository: quay.io/minio/minio
#   tag: RELEASE.2024-06-07T22-20-11Z
#   pullPolicy: IfNotPresent
# mcImage:
#   repository: quay.io/minio/mc
#   tag: RELEASE.2024-06-07T22-20-11Z
#   pullPolicy: IfNotPresent
# image: 
#  repository: quay.io/minio/mc
#  tag: RELEASE.2024-06-07T22-20-11Z
#  pullPolicy: IfNotPresent
# # image:
#   repository: quay.io/minio/minio
#   tag: RELEASE.2024-12-18T13-15-44Z
#   pullPolicy: IfNotPresent
replicas: 2