apiVersion: v1
kind: ConfigMap
metadata:
  name: cpu-scheduler-config
  namespace: kube-system
data:
  cpu-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: cpu-scheduler
        plugins:
          filter:
            enabled:
              - name: NodeResourcesFit
              - name: NodeAffinity
              - name: PodTopologySpread
              - name: TaintToleration
              - name: NodeUnschedulable
              - name: NodeName
          score:
            # only allow NodeResourcesFit; disable all other scoring plugins
            enabled:
              - name: NodeResourcesFit
            disabled:
              - name: "*"
        pluginConfig:
          - name: NodeResourcesFit
            args:
              scoringStrategy:
                type: LeastAllocated    # pick nodes with the fewest CPU requests
                resources:
                  - name: cpu
                    weight: 1          # CPU is the only resource we care about
