apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-loki-minio
  namespace: minio
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: loki
  data:
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: monitoring
      property: rootPassword
  - secretKey: AWS_SECRET_ACCESS_ID
    remoteRef:
      key: monitoring
      property: rootUser