postgres:
  settings:
    superuser:
      secretKeyRef:
        name: postgres-credentials
        key: superuser
    superuserPassword:
      secretKeyRef:
        name: postgres-credentials
        key: superuserPassword

  userDatabase:
    name:
      secretKeyRef:
        name: postgres-credentials
        key: dbName
    user:
      secretKeyRef:
        name: postgres-credentials
        key: dbUser
    password:
      secretKeyRef:
        name: postgres-credentials
        key: dbPassword