apiVersion: v1
name: kube-prometheus-stack
version: 0.0.0
dependencies: # A list of the chart requirements (optional)
  - name: kube-prometheus-stack
    version: 79.0.0
    repository: https://prometheus-community.github.io/helm-charts