# You can customize your values from this link https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack and click on "DEFAULT VALUES"
# NOTE all values in above reference it must my chiled of name of Application in Chart.yaml (for e.g in below)

kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: monitoring-credentials
      userKey: admin-user
      passwordKey: admin-password

  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname', 'namespace']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: n8n-llm
      receivers:
        - name: n8n-llm
          webhook_configs:
            - url: "http://n8n.n8n.svc:5678/webhook/alert"
              send_resolved: true