apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-monitoring-vault
  namespace: monitoring
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: monitoring-access-key
  data:
  - secretKey: admin-user
    remoteRef:
      key: monitoring
      property: userKey
  - secretKey: admin-password
    remoteRef:
      key: monitoring
      property: passwordKey
 

---
# will create a secret with:
# kind: Secret
# metadata:
#   name: example-sync
# data:
#   foobar: czNjcjN0