mongodb:
  architecture: replicaset  
  replicaCount: 1

  auth:
    enabled: true  
    rootUser: admin
    existingSecret: ""

  persistence:
    enabled: true  
    size: 10Gi  
    storageClass: ""  

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 1
  
  arbiter:
    enabled: false