apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - git:
        repoURL: https://github.com/n4if11/zahra
        revision: HEAD
        requeueAfterSeconds: 20
        files:
          - path: "apps/ai/**/config.yaml"
        values:
          name: "{{.path.basename}}"
  template:
    metadata:
      name: '{{ default .values.name .appName }}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{.values.name}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ default .values.name .destNamespace }}'
      project: default
      source:
        repoURL: '{{ default "https://github.com/n4if11/zahra" .repoURL }}'
        targetRevision: '{{ default "HEAD" .srcTargetRevision }}'
        path: '{{ default .path.path .srcPath }}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          limit: 30
          backoff:
            duration: 20s
            factor: 1
            maxDuration: 20s
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  templatePatch: |
    {{- if .noAutoSync }}
    spec:
      syncPolicy:
        automated: null
        retry:
          limit: 30
          backoff:
            duration: 20s
            factor: 1
            maxDuration: 20s
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
    {{- end }}
  syncPolicy: {}
