apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: monitoring-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: project-1/monitoring
        property: grafanaAdminUser
    - secretKey: admin-password
      remoteRef:
        key: project-1/monitoring
        property: grafanaAdminPassword
